### ISSUE TITLE
[question] pygments style

### ISSUE THREAD

**Issue by gares** [cpitclaudel/alectryon#58]
This comment seems outdated, since the .css is not inlined even if you use the command line interface.

```python
def highlight_html(coqstr):
    """Highlight a Coq string `coqstr`.

    Return a raw HTML string.  This function is just a convenience wrapper
    around Pygments' machinery, using a custom Coq lexer and a custom style.

    The generated code needs to be paired with a Pygments stylesheet, which can
    be generated by running the ``regen_tango_subtle_css.py`` script in the
    ``etc/`` folder of the Alectryon distribution.

    If you use Alectryon's command line interface directly, you won't have to
    jump through that last hoop: it renders and writes out the HTML for you,
    with the appropriate CSS inlined.  It might be instructive to consult the
    implementation of ``alectryon.cli.dump_html_standalone`` to see how the CLI
    does it."""
```

If it was inlined, I could add a command line option to select another style.

I'd like to pick another style, one close to the default vscode one.

One way would be to keep the css external, maybe rename it to remove "tango", and change the regen_tango_subtle_css.py to take an argument (the style), and the let me generate another style at deploy time.

Another option would be to make this comment true, and add a command line option to pick the style.

What is best?

**Comment by cpitclaudel** [comment]
I think Github lost my answer to this question, sorry.  Trying again:

> This comment seems outdated, since the .css is not inlined even if you use the command line interface.

It depends:

- With --frontend coq, it is unconditionally inlined.
- With --frontend coq+rst, it is inlined only if embed_stylesheets is non-nil.

> If it was inlined, I could add a command line option to select another style.

We could still have a CLI option to select the style, even if it's external (I think this is also what you say below?)

> One way would be to keep the css external, maybe rename it to remove "tango", and change the regen_tango_subtle_css.py to take an argument (the style), and the let me generate another style at deploy time.

Right.

> Another option would be to make this comment true, and add a command line option to pick the style.

Right.

> What is best?

I'm not sure :)  Both?  I've made a branch at https://github.com/cpitclaudel/alectryon/tree/gh-58-pygments ; please give it a try and let me know what you think.  In brief:

- You can pick a style with --pygments-style
- It should inline correctly based on `embed_stylesheet`
- The generated stylesheet is called `pygments.css` instead of `tango_subtle`
- When building with Sphinx, it respects Sphinx's `--pygments-style` settings.

Hopefully that covers everything.  Please let me know, and I'll merge soon.

**Comment by gares** [comment]
great, I'll try asap

**Comment by gares** [comment]
Works for me, thanks!

**Comment by cpitclaudel** [comment]
Thanks, merged.
