### ISSUE TITLE
Bump version and add -dev to version number for main branch

### ISSUE THREAD

**Issue by jjhugues** [cpitclaudel/alectryon#67]
Hi, it would be useful to add a -dev for alectryon --version when updating from the git repo

In other words
```
➜  docs git:(main) ✗ alectryon --version
Alectryon v1.3.1
```

should report v1.3.2-dev instread, until you release it

I had both a pip3 install and a manual install for #66 and had to debug a couple of things to ensure I had the right files installed

**Comment by cpitclaudel** [comment]
Is there a guideline somewhere about this? I think `-dev` is not a valid Python version number and I can't find anything about the proper version number to keep in the repo (Big Python packages seem to keep the last released number).

There us also the issue of what version number I should use in there: I don't know yet what the next version number will be (it depends on the scope of the changes).

**Comment by jjhugues** [comment]
Right, `-dev` might be problematic. See https://packaging.python.org/guides/distributing-packages-using-setuptools/#choosing-a-versioning-scheme for suggestions. 1.3.2.dev could work.

Since you are concerned that main could become a 2.0, why not 1.3.1.post ?

**Comment by cpitclaudel** [comment]
PEP 440 says "Some projects use post-releases to address minor errors in a final release that do not affect the distributed software (for example, correcting an error in the release notes). If used as part of a project's development cycle, these post-releases are indicated by including a post-release segment in the version identifier", so I don't think `.post` is the way to go.  There doesn't seem to be much consensus in the community; Sphinx uses `3.2.5+`, for example, which doesn't even compare correctly with `pkg_resources.parse_version`.

I've changed the repo version number to `1.3.2-dev`, since in fact the normalization algorithm in PEP 440 allows the hyphen (I was wrong about that earlier).
