### ISSUE TITLE
Support/Dependency versions for Coq 8.11 and 8.12

### ISSUE THREAD

**Issue by Blaisorblade** [cpitclaudel/alectryon#7]
Congrats on the release! I was upgrading our code to Coq 8.12, and was wondering whether that's supported — the README doesn't say.

- The README instructs to install `opam install coq-serapi=8.10.0+0.7.0` (and yes, it depends on `"coq" {>= "8.10.0" & < "8.11"}` as you'd expect).
- On 8.11 we've used `coq-serapi.8.11.0+0.11.0` for a while, there's also `coq-serapi.8.11.0+0.11.1`
- On 8.12 the only available release is `coq-serapi=8.12.0+0.12.0`.

**Comment by cpitclaudel** [comment]
Thanks :)

I've been cautious about making claims about supported versions mostly because I haven't set up a CI yet; I'd love help with that if you or someone who comes across this issue has time :) 

IIUC SerAPI's versioning scheme is that version X.Y+* of SerAPI corresponds to version X.Y.* of coq.  My plan is mostly to follow SerAPI in deciding what's supported, so at the moment with Alectryon you'd use latest SerAPI 8.10+*, 8.11+*, or 8.12+*, and all three should work.  Would it help to be more precise than this (promising to support not just SerAPI X.Y+latest but SerAPI X.Y+Z for a specific Z?)

(One note: I want to start passing `-topfile` soon, but since Emilio released a new version of SerAPI 8.10 with that feature it shouldn't break anything beyond requiring a SerAPI update from 8.10.0+0.7.0 to 8.10.0+0.7.1).

**Comment by Blaisorblade** [comment]
Until there’s CI, "We hope that we support Coq 8.10-8.12 but for now we only test 8.10" would prevent these questions. (I'd guess we used 8.11+0.11.0 plenty?).

- Uh, I don’t have time right now, but maybe?

> Would it help to be more precise than this (promising to support not just SerAPI X.Y+latest but SerAPI X.Y+Z for a specific Z?)

I’d indeed pick that Z that you recommend: AFAIK we’re devout Alectryon followers, so we only use serapi for Alectryon and no other gods 🙃 . And we’ll install whichever SerAPI version Alectryon recommends.

Considering other users, not sure what’s reasonable for you to support — it’s currently your time. The docs should reflect what you do I guess? Say, after a new SerAPI release, is it supported immediately or do you need to test the code? In the latter case, you could bump the README after you do the testing.

**Comment by Zimmi48** [comment]
Despite what it README claims, SerAPI is pretty stable so I wouldn't be surprised if the claim "all versions above X" was sufficient.

**Comment by cpitclaudel** [comment]
Done, I've updated the readme to say ≥ 8.10.  I've also relaxed the version list for Python packages.
